services:
  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./common/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  fetcher:
    build:
      context: .
      dockerfile: fetcher/Dockerfile
    env_file:
      - .env
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  db-data:
